### ISSUE TITLE
Koth reload error

### ISSUE THREAD

**Issue by cloakfox** [SubSide/KOTH#75] opened 2017-06-11 11:09 UTC
Error: https://pastebin.com/eSbqqZq8
Using PaperSpigot 1.8.8

**Comment by SubSide** [comment] 2017-06-11 18:59
Caused by the BossBarAPI, which is not supported in 1.8.8
Fixed by disabling the bossbar hook in the config (and installing an updated version of the Koth2BarAPI bridge)

**Closed by SubSide** 2017-06-11 18:59 UTC
Labels: bug, invalid
